#
# SPARQL-query for processing of an item matched by a shoppinglist
#
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX sl: <http://uduvudu.me/vocab/shoppinglist#>
PREFIX purchaser: <http://uduvudu.me/purchaser#>

SELECT ?data ?p ?o
WHERE {
        ?data a purchaser:Data .
        ?data ?p ?o .
}
